### ISSUE TITLE
Wrap imported components in readme with { }

### ISSUE THREAD

**Issue by jacobmakarsky** [tsamantanis/react-glassmorphism#1]
Hello,

Was getting an issue with the imports from the examples in ReadMe. Realized it needed the { }. For ex:

`import { CustomCard } from '@tsamantanis/react-glassmorphism'
`

Might be issue specific to my project but might help other users.

Thanks 👍

**Comment by tsamantanis** [comment]
Just updated the documentation for this. Thanks for reaching out!
